Add carbon metrics to get dashboard support
siddhi-io/siddhi-io-file pull request #93
Opened 2020-04-15 14:27 UTC by sahandilshan

## Purpose
> $subject

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

2020-06-03 13:21 UTC, ramindu90 requested changes

2020-06-03 13:21 UTC, ramindu90 commented on component/src/main/java/io/siddhi/extension/execution/file/FileCopyExtension.java
> +                        "prometheus")) {
Shall we make this a constant? Maybe it should be a constant in the carbon metrics package.

2020-06-03 13:21 UTC, ramindu90 commented on component/src/main/java/io/siddhi/extension/execution/file/FileCopyExtension.java
> +                log.debug("Prometheus reporter is not running. Hence file metrics will not be initialise in "
Maybe this should be rephrased as "will not be initialized"

2020-06-03 13:21 UTC, ramindu90 commented on component/src/main/java/io/siddhi/extension/io/file/metrics/FileMoveMetrics.java
> +                .gauge(String.format("io.siddhi.SiddhiApps.%s.Siddhi.File.Operations.Move.%s.%s.%s",
Cant change to have 1 metric class and pass "io.siddhi.SiddhiApps.%s.Siddhi.File.Operations.Move.%s.%s.%s" when creating and retrieving the metric?

2020-06-03 15:22 UTC, sahandilshan commented on component/src/main/java/io/siddhi/extension/execution/file/FileCopyExtension.java
> +                        "prometheus")) {
This was fix in 85ee5fb1ca9a98ffc21692e9a468773fc49cacba, There's no constant available in the carbon metrics, Hence introduce as a new constant.

2020-06-03 15:22 UTC, sahandilshan commented on component/src/main/java/io/siddhi/extension/execution/file/FileCopyExtension.java
> +                log.debug("Prometheus reporter is not running. Hence file metrics will not be initialise in "
This was fixed in 85ee5fb1ca9a98ffc21692e9a468773fc49cacba

2020-06-04 06:14 UTC, ramindu90 approved these changes

2020-06-04 06:14 UTC, merged